=== ftctechnh/ftc_app/SiBorgs6188/build/intermediates/merged_assets/debug/mergeDebugAssets/out/RobotConfigTaxonomy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="RobotConfigTaxonomy">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element name="Sensor" type="Sensor"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Sensor">
		<xs:sequence>
			<xs:element name="XmlTag" type="xs:string"/>
			<xs:element name="Description" type="xs:string"/>
			<xs:element name="Bus" type="xs:string"/>
			<xs:element name="BusDefault" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== ftctechnh/ftc_app/SiBorgs6188/build/intermediates/merged_assets/debug/mergeDebugAssets/out/RobotConfigTaxonomy.xml
<?xml version="1.0" encoding="UTF-8"?>
<RobotConfigTaxonomy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="RobotConfigTaxonomy.xsd">
	<Sensor>
		<XmlTag>Motor</XmlTag>
		<Description>a motor</Description>
		<Bus>nobus</Bus>
		<BusDefault>port</BusDefault>
	</Sensor>
	<Sensor>
		<XmlTag>Servo</XmlTag>
		<Description>a servo</Description>
		<Bus>nobus</Bus>
		<BusDefault>port</BusDefault>
	</Sensor>
	<Sensor>
		<XmlTag>ContinuousRotationServo</XmlTag>
		<Description>a continuous rotation servo</Description>
		<Bus>nobus</Bus>
		<BusDefault>port</BusDefault>
	</Sensor>
	<Sensor>
		<XmlTag>Compass</XmlTag>
		<Description>a compass seeker</Description>
		<Bus>nobus</Bus>
		<BusDefault>port</BusDefault>
	</Sensor>
	<Sensor>
		<XmlTag>LightSensor</XmlTag>
		<Description>a light sensor</Description>
		<Bus>nobus</Bus>
		<BusDefault>port</BusDefault>
	</Sensor>
	<Sensor>
		<XmlTag>Accelerometer</XmlTag>
		<Description>an accelerometer</Description>
		<Bus>nobus</Bus>
		<BusDefault>port</BusDefault>
	</Sensor>
	<Sensor>
		<XmlTag>TouchSensorMultiplexer</XmlTag>
		<Description>a touch sensor multiplexer</Description>
		<Bus>nobus</Bus>
		<BusDefault>port</BusDefault>
	</Sensor>
	<Sensor>
		<XmlTag>UltrasonicSensor</XmlTag>
		<Description>an ultrasonic sensor</Description>
		<Bus>nobus</Bus>
		<BusDefault>port</BusDefault>
	</Sensor>
	<Sensor>
		<XmlTag>OpticalDistanceSensor</XmlTag>
		<Description>an optical distance sensor</Description>
		<Bus>nobus</Bus>
		<BusDefault>analog input port</BusDefault>
	</Sensor>
	<Sensor>
		<XmlTag>AnalogInput</XmlTag>
		<Description>an analog input device</Description>
		<Bus>nobus</Bus>
		<BusDefault>analog input port</BusDefault>
	</Sensor>
	<Sensor>
		<XmlTag>TouchSensor</XmlTag>
		<Description>a touch sensor</Description>
		<Bus>digitalbus</Bus>
		<BusDefault>port</BusDefault>
	</Sensor>
	<Sensor>
		<XmlTag>LED</XmlTag>
		<Description>an LED</Description>
		<Bus>digitalbus</Bus>
		<BusDefault>port</BusDefault>
	</Sensor>
	<Sensor>
		<XmlTag>DigitalDevice</XmlTag>
		<Description>a digital device</Description>
		<Bus>digitalbus</Bus>
		<BusDefault>port</BusDefault>
	</Sensor>
	<Sensor>
		<XmlTag>IrSeeker</XmlTag>
		<Description>an IR seeker</Description>
		<Bus>i2cbus</Bus>
		<BusDefault>port</BusDefault>
	</Sensor>
	<Sensor>
		<XmlTag>ColorSensor</XmlTag>
		<Description>a color sensor</Description>
		<Bus>i2cbus</Bus>
		<BusDefault>port</BusDefault>
	</Sensor>
	<Sensor>
		<XmlTag>AdaFruitColorSensor</XmlTag>
		<Description>an Adafruit color sensor</Description>
		<Bus>i2cbus</Bus>
		<BusDefault>port</BusDefault>
	</Sensor>
	<Sensor>
		<XmlTag>Gyro</XmlTag>
		<Description>a gyroscope</Description>
		<Bus>i2cbus</Bus>
		<BusDefault>port</BusDefault>
	</Sensor>
	<Sensor>
		<XmlTag>I2cDevice</XmlTag>
		<Description>an I2C device</Description>
		<Bus>i2cbus</Bus>
		<BusDefault>port</BusDefault>
	</Sensor>
	<Sensor>
		<XmlTag>I2cDeviceSynch</XmlTag>
		<Description>an I2C device</Description>
		<Bus>i2cbus</Bus>
		<BusDefault>port</BusDefault>
	</Sensor>
	<Sensor>
		<XmlTag>PulseWidthDevice</XmlTag>
		<Description>a pulse-width device</Description>
		<Bus>pwmbus</Bus>
		<BusDefault>PWM port</BusDefault>
	</Sensor>
	<Sensor>
		<XmlTag>AnalogOutput</XmlTag>
		<Description>an analog output device</Description>
		<Bus>aobus</Bus>
		<BusDefault>analog output port</BusDefault>
	</Sensor>
	<Sensor>
		<XmlTag>RevRoboticsCoreHexMotor</XmlTag>
		<Description>a REV Robotics Core Hex Motor</Description>
		<Bus>nobus</Bus>
		<BusDefault>port</BusDefault>
	</Sensor>
	<Sensor>
		<XmlTag>LynxEmbeddedIMU</XmlTag>
		<Description>the internal IMU</Description>
		<Bus>i2cbus</Bus>
		<BusDefault>port</BusDefault>
	</Sensor>
</RobotConfigTaxonomy>
